import sys

TEST_WORKSPACE = sys.path[0]

TEST_DIR_NAME = "tests"
TEST_FILES_NAME = "test_files"

DELETE_SCRIPT_TEST_INPUT_DIR = False
DELETE_SCRIPT_TEST_OUTPUT_DIR = False
DELETE_SCRIPT_TEST_DIR = False
