
ARG PYTHON_VERSION=3.11

# Built .exe replay parsing tool is required to run sc2_replaypack_processor
# https://github.com/Kaszanas/SC2InfoExtractorGo
FROM kaszanas/sc2infoextractorgo:dev AS extractor
FROM kaszanas/sc2reset_maps_mods:latest AS maps_mods

FROM python:${PYTHON_VERSION} AS base

ENV TEST_WORKSPACE=/app

# Install other dependencies such as git, etc. This is needed for
# pre-commit hooks to work and other QOL stuff.
RUN apt-get update && apt-get install -y --no-install-recommends \
    make build-essential libssl-dev wget ca-certificates curl llvm git vim bash

WORKDIR /app

# Copying the replay parsing tool:
# sc2egset_replaypack_processor requires the .exe file to be in the same directory as the script:
COPY --from=extractor /app/SC2InfoExtractorGo /app/SC2InfoExtractorGo
COPY --from=maps_mods /sc2reset_maps_mods/maps/ /app/processing/maps/
COPY --from=maps_mods /sc2reset_maps_mods/other_dependencies/ /app/processing/other_dependencies/

# Ensure the executable has the right permissions:
RUN chmod +x /app/SC2InfoExtractorGo

# Install uv:
COPY --from=ghcr.io/astral-sh/uv:0.5.11 /uv /uvx /bin/

# Copy only what is required to install the project:
COPY pyproject.toml uv.lock /app/

# Install only dependencies without installing current project:
RUN uv sync --no-install-project

# Ensure the uv-managed virtual environment is used without needing explicit activation:
ENV PATH="/app/.venv/bin:$PATH"


# Required for CI and pre-commit locally:
COPY .pre-commit-config.yaml /app/.pre-commit-config.yaml

# Required to install pre-commit in future steps:
COPY .git/ /app/.git/

# Copy test files:
COPY /src/ /app/src/
COPY /tests/__init__.py /app/tests/__init__.py
COPY /tests/conftest.py /app/tests/conftest.py
COPY /tests/test_utils.py /app/tests/test_utils.py
COPY /tests/test_settings.py /app/tests/test_settings.py
COPY /tests/test_main.py /app/tests/test_main.py
COPY /tests/test_cases/ /app/tests/test_cases/
RUN mkdir -p /tests/test_files/

# Copy docs files:
COPY /docs/ /app/docs/
COPY mkdocs.yml /app/mkdocs.yml
COPY README.md /app/README.md
COPY CONTRIBUTING.md /app/CONTRIBUTING.md

# Bring the scripts to the top level.
# They import parts of the project but as long as the project is installed
# in the same environment, they can run from anywhere as long as the environment
# is activated.
COPY /src/datasetpreparator/directory_flattener/directory_flattener.py \
    /src/datasetpreparator/directory_packager/directory_packager.py \
    /src/datasetpreparator/file_renamer/file_renamer.py \
    /src/datasetpreparator/json_merger/json_merger.py \
    /src/datasetpreparator/processed_mapping_copier/processed_mapping_copier.py \
    /src/datasetpreparator/sc2/sc2_map_downloader/sc2_map_downloader.py \
    /src/datasetpreparator/sc2/sc2egset_replaypack_processor/sc2egset_replaypack_processor.py \
    /src/datasetpreparator/sc2/sc2egset_replaypack_processor/sc2egset_pipeline.py \
    /src/datasetpreparator/sc2/sc2reset_replaypack_downloader/sc2reset_replaypack_downloader.py \
    /src/datasetpreparator/sc2/sc2_update_maps_cache/sc2_update_maps_cache.py \
    /src/datasetpreparator/sc2/sc2_move_maps/sc2_move_maps.py \
    /app/


RUN uv run pre-commit install

# Install current project:
RUN uv sync --all-extras
