# Built .exe replay parsing tool is required to run sc2_replaypack_processor
# https://github.com/Kaszanas/SC2InfoExtractorGo

ARG PYTHON_VERSION=3.11

FROM python:${PYTHON_VERSION}-alpine

WORKDIR /app

# Copy only what is required to install the project:
COPY pyproject.toml poetry.lock /app/

# Install only dependencies without installing current project:
RUN poetry config virtualenvs.create false && poetry install --no-root

# Copy entire repository contents
COPY . .

# Install current project:
RUN poetry install

CMD ["bash"]
